spring.datasource.url=jdbc:postgresql://dpg-d9qoasqjnfac73dsvlp0-a/dbnamew2
spring.datasource.username=dbuser
spring.datasource.password=7jOvhbTqn9xZahPUrMxnIsFztZjgKWS9

spring.jpa.hibernate.ddl-auto=update
#show sql requests in log
spring.jpa.show-sql=false
#to show formated message
spring.jpa.properties.hibernate.format_sql=false