spring.datasource.url=jdbc:postgresql://dpg-d9qoasqjnfac73dsvlp0-a/dbnamew2
spring.datasource.username=dbuser
spring.datasource.password=7jOvhbTqn9xZahPUrMxnIsFztZjgKWS9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
