# If you whant to run on local set profiles.active - local, to run on Render Postgres - pg
#spring.profiles.active=local
spring.profiles.active=pg
spring.jackson.time-zone=Europe/Moscow
spring.jpa.properties.hibernate.jdbc.time_zone=UTC