spring.datasource.url=jdbc:postgresql://dpg-d9at3tuq1p3s73dahlj0-a/dbname_saba
spring.datasource.username=dbuser
spring.datasource.password=SfUicS5SiwPbm4Cl72hdPrqXptX04rcC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
