spring.datasource.url=jdbc:postgresql://dpg-dae2p97qj5pc73a1t1gg-a/pg09
spring.datasource.username=dbuser
spring.datasource.password=XamObbqp0RNRLJBqO2IuuxWdKArKQ2Pc

spring.jpa.hibernate.ddl-auto=update
#show sql requests in log
spring.jpa.show-sql=false
#to show formated message
spring.jpa.properties.hibernate.format_sql=false